# Generated by Django 4.2.6 on 2023-10-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentTemperature', models.IntegerField(max_length=2)),
                ('modified', models.BooleanField(default=False)),
            ],
        ),
    ]
